In [1]:
import numpy as np

In [19]:
vector1 = np.array([100, 3, 1, -999])
vector2 = np.array([-300, -5, 70, 3])

In [20]:
a = np.dot(vector1, vector2)/np.linalg.norm(vector2)**2
a

-0.34699896770387845

In [21]:
vector3 = vector1 - a*vector2

In [22]:
vector3

array([  -4.09969031,    1.26500516,   25.28992774, -997.9590031 ])

In [23]:
np.dot(vector2, vector3)

-5.4569682106375694e-12

In [24]:
a*vector2 + vector3

array([ 100.,    3.,    1., -999.])

In [25]:
np.linalg.norm(vector3)

998.2886155846409

In [26]:
vector4 = vector3 / np.linalg.norm(vector3)
vector4

array([-0.00410672,  0.00126717,  0.02533328, -0.99966982])

In [27]:
np.linalg.norm(vector4)

1.0